AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template for Creating a CodeBuild Project to Run Tests'

Parameters:
  GitHubSourceRepoURL:
    Type: String
    Description: "The URL of the GitHub repository where the source code is located."
  WebsiteURL:
    Type: String
    Description: "Website URL"
  ArtifactBucket:
    Type: String
    Description: The name of the S3 bucket where build artifacts will be stored.
  ArtifactBucketKeyPrefix:
    Type: String
    Default: 'artifacts/acceptance_tests'
    Description: The directory in the S3 bucket where build artifacts will be stored.

Resources:
  AcceptanceTestsBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [codebuild.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: "/"
      Policies:
        - PolicyName: CodeBuildPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource:
                  - !Sub 'arn:aws:s3:::${ArtifactBucket}/${ArtifactBucketKeyPrefix}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${ArtifactBucket}'

  WebsiteAcceptanceTestsProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AWS::StackName}-WebsiteAcceptanceTestsProject"
      Description: "CodeBuild project to run automated acceptance tests for the website"
      ServiceRole: !GetAtt AcceptanceTestsBuildRole.Arn
      Artifacts:
        Type: S3
        Location: !Ref ArtifactBucket
        Packaging: ZIP
        Path: !Ref ArtifactBucketKeyPrefix
        NamespaceType: BUILD_ID
      Source:
        Type: GITHUB
        Location: !Ref GitHubSourceRepoURL
        BuildSpec: 'src/website/tests/buildspec.yml'
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        EnvironmentVariables:
          - Name: WEBSITE_URL
            Value: !Ref WebsiteURL
            Type: PLAINTEXT
      TimeoutInMinutes: 5

  DailyBuildTrigger:
    Type: AWS::Events::Rule
    Properties:
      Description: Trigger for daily builds
      ScheduleExpression: 'cron(0 12 * * ? *)'
      State: ENABLED
      Targets:
        - Arn: !GetAtt WebsiteAcceptanceTestsProject.Arn
          Id: "DailyBuildAcceptanceTests"
          RoleArn: !GetAtt AcceptanceTestsBuildRole.Arn
