AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Application Load Balancer.

Parameters:
  VpcId:
    Description: VPC ID where the ALB will be deployed.
    Type: AWS::EC2::VPC::Id
  SubnetIds:
    Description: Subnet ID where the ALB will be deployed.
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroupId:
    Description: Security Group ID for the ALB.
    Type: AWS::EC2::SecurityGroup::Id
  EC2InstanceId:
    Description: 'EC2 Instance ID to be registered with the ALB'
    Type: AWS::EC2::Instance::Id
  # EC2InstanceIds:
  #   Description: 'EC2 Instance ID to be registered with the ALB'
  #   Type: List<AWS::EC2::Instance::Id>
  SiteCertificateArn:
    Description: ARN of the certificate
    Type: String
  ALBName:
    Description: Name for the Application Load Balancer.
    Type: String
    Default: "WordpressApplicationLoadBalancer"
  ALBScheme:
    Description: Scheme for the ALB (internal or internet-facing).
    Type: String
    AllowedValues:
      - internet-facing
      - internal
    Default: internet-facing
  ALBProtocol:
    Description: Protocol for ALB Listener (HTTP or HTTPS).
    Type: String
    AllowedValues:
      - HTTP
      - HTTPS
    Default: HTTP
  ALBPort:
    Description: Port for ALB Listener.
    Type: Number
    Default: 80
  TargetGroupProtocol:
    Description: Protocol for ALB Listener (HTTP or HTTPS).
    Type: String
    AllowedValues:
      - HTTP
      - HTTPS
    Default: HTTP
  TargetGroupPort:
    Description: Port for ALB Listener.
    Type: Number
    Default: 80

Resources:
  WordpressALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref ALBName
      Scheme: !Ref ALBScheme
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref SecurityGroupId
      Type: application

  WordpressApplicationsTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: "wordpress-app-tier-tg"
      Port: !Ref TargetGroupPort
      Protocol: !Ref TargetGroupProtocol
      VpcId: !Ref VpcId
      Targets:
        - Id: !Ref EC2InstanceId
      TargetType: instance
      HealthCheckPath: "/"
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200-301

  WordpressALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref WordpressALB
      Protocol: HTTPS  # Set to HTTPS
      Port: 443  # Set to 443 for HTTPS
      SslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
      Certificates:
        - CertificateArn: !Ref SiteCertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WordpressApplicationsTargetGroup

Outputs:
  ALBArn:
    Description: ARN of the ALB.
    Value: !Ref WordpressALB

