AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  S3BucketName:
    Type: String
    Description: The name of the S3 bucket for storing logs.
    Default: 'wordpress'

Resources:
  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-${S3BucketName}"

  ALBLogPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy to allow ALB to write logs
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${LogBucket}/logs/alb/*'

  CloudFrontLogPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy to allow CloudFront to write logs
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${LogBucket}/logs/cloudfront/*'

Outputs:
  LogBucket:
    Value: !Ref LogBucket
  ALBLogPolicyArn:
    Value: !Ref ALBLogPolicy
  CloudFrontLogPolicyArn:
    Value: !Ref CloudFrontLogPolicy
