AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to add an A record to a Route53 hosted zone.

Parameters:
  ApexDomainName:
    Description: 'The name of the apex A record (e.g. example.com.)'
    Type: 'String'
    AllowedPattern: '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'
    ConstraintDescription: 'Must be a valid DNS name format (e.g., example.com.)'

  HostedZoneId:
    Description: 'The ID of the Route53 hosted zone where the record(s) will be created'
    Type: 'String'

  ApexIpAddress:
    Description: 'The IP address for the A record'
    Type: 'String'
    # AllowedPattern: '^(\d{1,3}\.){3}\d{1,3}$'
    ConstraintDescription: 'Must be a valid IP address format (e.g., 192.168.1.10)'
    Default: ''

  ApexDNSName:
    Description: The DNS name of the Application Load Balancer.
    Type: String
    Default: ''
  ApexDNSHostedZoneId:
    Description: The hosted zone ID where the Application Load Balancer is located.
    Type: String
    Default: ''

Conditions:
  CreateIPAddressApexRecord: !Not [ !Equals [ !Ref ApexIpAddress, '' ] ]
  ApexDNSNameExists: !Not [ !Equals [ !Ref ApexDNSName, '' ] ]
  ApexDNSHostedZoneIdExists: !Not [ !Equals [ !Ref ApexDNSHostedZoneId, '' ] ]
  CreateALBApexRecord: !And
    - !Condition ApexDNSNameExists
    - !Condition ApexDNSHostedZoneIdExists

Resources:
  ApexARecord:
    Type: 'AWS::Route53::RecordSet'
    Condition: CreateIPAddressApexRecord
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref ApexDomainName
      Type: 'A'
      TTL: '300'
      ResourceRecords:
        - !Ref ApexIpAddress

  ApexDomainAliasRecord:
    Type: 'AWS::Route53::RecordSet'
    Condition: CreateALBApexRecord
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref ApexDomainName
      Type: A
      AliasTarget:
        HostedZoneId: !Ref ApexDNSHostedZoneId
        DNSName: !Ref ApexDNSName

  WwwAliasRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "www.${ApexDomainName}"
      Type: A
      AliasTarget:
        HostedZoneId: !Ref HostedZoneId
        DNSName: !Ref ApexDomainName
