AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Secrets Manager secrets, IAM role, and associated IAM policy.

Parameters:
  DatabasePassword:
    Description: The password for the database.
    Type: String
    NoEcho: true

  WordPressAdminPassword:
    Description: The password for the WordPress admin.
    Type: String
    NoEcho: true

Resources:
  DatabasePasswordSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: database-password-secret
      Description: Password for the database connection.
      SecretString: !Ref DatabasePassword

  WordPressAdminPasswordSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: wordpress-admin-password-secret
      Description: Password for the WordPress admin.
      SecretString: !Ref WordPressAdminPassword

  WordpressEc2SecretsAccessManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Ref DatabasePasswordSecret
              - !Ref WordPressAdminPasswordSecret

Outputs:
  WordpressEc2SecretsAccessManagedPolicy:
    Description: WordpressEc2SecretsAccessManagedPolicy
    Value: !Ref WordpressEc2SecretsAccessManagedPolicy
  DatabasePasswordSecretArn:
    Description: The ARN of the database password secret.
    Value: !Ref DatabasePasswordSecret
  WordpressAdminPasswordSecretArn:
    Description: The ARN of the WordPress admin password secret.
    Value: !Ref WordPressAdminPasswordSecret
