AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to add an A record to a Route53 hosted zone.

Parameters:
  IPAddress:
    Description: 'The IP address for the A record'
    Type: 'String'
    AllowedPattern: '^(\d{1,3}\.){3}\d{1,3}$'
    ConstraintDescription: 'Must be a valid IP address format (e.g., 192.168.1.10)'

  HostedZoneId:
    Description: 'The ID of the Route53 hosted zone where the record will be created'
    Type: 'String'

  RecordName:
    Description: 'The name of the apex A record (e.g., example.com.)'
    Type: 'String'
    AllowedPattern: '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'
    ConstraintDescription: 'Must be a valid DNS name format (e.g., example.com.)'

Resources:
  ApexARecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref RecordName
      Type: 'A'
      TTL: '300'
      ResourceRecords:
        - !Ref IPAddress

  WwwARecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "www.${RecordName}"
      Type: 'A'
      TTL: '300'
      ResourceRecords:
        - !Ref IPAddress

Outputs:
  RecordSetId:
    Description: 'The ID of the created record set'
    Value: "ApexARecord"
