AWSTemplateFormatVersion: '2010-09-09'
Description: Instance profile for wordpress ec2 instance(s).

Parameters:
  ManagedPolicyArnList:
    Description: List of managed policy ARNs to attach to the role.
    Type: List<String>

Resources:
  WordpressEc2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns: !Ref ManagedPolicyArnList

  WordpressInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: '/'
      Roles:
      - Ref: WordpressEc2InstanceRole

Outputs:
  WordpressInstanceProfile:
    Description: 'ID of the EC2 instance'
    Value: !Ref WordpressInstanceProfile
