AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  S3BucketName:
    Type: String
    Description: The name of the S3 bucket for storing logs.
    Default: 'wordpress'
  ELBAccountId:
    Type: String
    Description: A account ID for the relevant region pulled from https://docs.aws.amazon.com/elasticloadbalancing/latest/application/enable-access-logging.html
    Default: '033677994240'

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-${S3BucketName}"

  AccessLogsPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${ELBAccountId}:root"
            Action: s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${Bucket}/logs/alb/*'
            Condition:
              StringEquals:
                "s3:x-amz-acl": "bucket-owner-full-control"
          - Effect: Allow
            Principal:
              Service: elasticloadbalancing.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${Bucket}/logs/cloudfront/*'
            Condition:
              StringEquals:
                "s3:x-amz-acl": "bucket-owner-full-control"
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
            Resource: !Sub 'arn:aws:s3:::${Bucket}/artifacts/*'

Outputs:
  Bucket:
    Value: !Ref Bucket
