AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront Distribution for WordPress with HTTPS support

Parameters:
  OriginDomainName:
    Description: The origin domain name (e.g. alb-1234567890.us-west-2.elb.amazonaws.com)
    Type: String
  Aliases:
    Description: Comma-separated list of aliases for the CloudFront distribution (e.g., www.example.com,example.com)
    Type: List<String>
  SiteCertificateArn:
    Description: ARN of the certificate
    Type: String

Resources:
  WordPressCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: CloudFront distribution tailored for WordPress on AWS
        Origins:
          - Id: WordPressOrigin
            DomainName: !Ref OriginDomainName
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        Aliases: !Ref Aliases
        ViewerCertificate:
          AcmCertificateArn: !Ref SiteCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1
        CacheBehaviors:
          - PathPattern: wp-includes/*
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            DefaultTTL: 900
            MaxTTL: 900
            MinTTL: 900
            ForwardedValues:
              QueryString: true
              Headers:
                - Host
            TargetOriginId: WordPressOrigin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
          - PathPattern: wp-content/*
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            DefaultTTL: 900
            MaxTTL: 900
            MinTTL: 900
            ForwardedValues:
              QueryString: true
              Headers:
                - Host
            TargetOriginId: WordPressOrigin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          ForwardedValues:
            QueryString: true
            Headers:
              - '*'
            Cookies:
              Forward: all
          TargetOriginId: WordPressOrigin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
        PriceClass: PriceClass_100

Outputs:
  DistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref WordPressCloudFrontDistribution
