AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Application Load Balancer with HTTPS.

Parameters:
  VpcId:
    Description: VPC ID where the ALB will be deployed.
    Type: AWS::EC2::VPC::Id
  SubnetIds:
    Description: Subnet IDs where the ALB will be deployed. Provide at least two for high availability.
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroupId:
    Description: Security Group ID for the ALB.
    Type: AWS::EC2::SecurityGroup::Id
  EC2InstanceId:
    Description: 'EC2 Instance ID to be registered with the ALB'
    Type: AWS::EC2::Instance::Id
  SiteCertificateArn:
    Description: ARN of the certificate for HTTPS
    Type: String
  AccessLogsS3Bucket:
    Description: The name of the S3 bucket for storing ALB access logs.
    Type: String
  AccessLogsS3Prefix:
    Description: The prefix (if any) for the access logs in the S3 bucket.
    Type: String
    Default: ""
  ALBName:
    Description: Name for the Application Load Balancer.
    Type: String
    Default: "WordpressApplicationLoadBalancer"
  ALBScheme:
    Description: Scheme for the ALB (internal or internet-facing).
    Type: String
    AllowedValues:
      - internet-facing
      - internal
    Default: internet-facing

Resources:
  WordpressALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref ALBName
      Scheme: !Ref ALBScheme
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref SecurityGroupId
      Type: application
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: true
        - Key: access_logs.s3.bucket
          Value: !Ref AccessLogsS3Bucket
        - Key: access_logs.s3.prefix
          Value: !Ref AccessLogsS3Prefix

  WordpressApplicationsTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: wordpress-app-tier-tg
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      Targets:
        - Id: !Ref EC2InstanceId
      TargetType: instance
      HealthCheckPath: "/"
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200-301

  WordpressALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref WordpressALB
      Protocol: HTTPS
      Port: 443
      SslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
      Certificates:
        - CertificateArn: !Ref SiteCertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WordpressApplicationsTargetGroup

Outputs:
  ALBArn:
    Description: ARN of the ALB.
    Value: !Ref WordpressALB
