AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a public subnet

Parameters:
  VpcId:
    Description: 'VPC ID where the subnet will be created'
    Type: 'AWS::EC2::VPC::Id'
    ConstraintDescription: Must be a valid VPC ID.

  WebTierCidrBlock:
    Description: 'CIDR block for the public subnet'
    Type: 'String'
    Default: '10.0.2.0/27'
    ConstraintDescription: Must be a valid CIDR block.

  ApplicationTierCidrBlock:
    Description: 'CIDR block for the public subnet'
    Type: 'String'
    Default: '10.0.3.0/27'
    ConstraintDescription: Must be a valid CIDR block.

  DataTierCidrBlock:
    Description: 'CIDR block for the public subnet'
    Type: 'String'
    Default: '10.0.4.0/27'
    ConstraintDescription: Must be a valid CIDR block.

Resources:
  WebTierSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref WebTierCidrBlock
      MapPublicIpOnLaunch: true

  ApplicationTierSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref ApplicationTierCidrBlock

  DataTierSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref DataTierCidrBlock

Outputs:
  WebTierSubnetId:
    Description: 'ID of the created public subnet'
    Value: !Ref WebTierSubnet
    Export:
      Name: WebTierSubnetId

  ApplicationTierSubnetId:
    Description: 'ID of the created public subnet'
    Value: !Ref WebTierSubnet
    Export:
      Name: ApplicationTierSubnetId

  DataTierSubnetId:
    Description: 'ID of the created public subnet'
    Value: !Ref WebTierSubnet
    Export:
      Name: DataTierSubnetId
